Repository SpaiR/imgui-java, pull requests merged in 2022-03, with the labels that each got.

#116 [API] Update lwjgl from 3.3.0 to 3.3.1
  README.md
  build.gradle
Labels: api

#115 ImPlot Performance Improvement
  imgui-binding/src/main/java/imgui/extension/implot/ImPlot.java
Labels: api

#117 [Doc] Repository documentation
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/missing_bindings.yml
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .github/workflows/update_natives.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#121 Support
  .github/FUNDING.yml
  README.md
Labels: documentation

#122 Adjust module name depending on deploy type
  imgui-binding-natives/build.gradle
Labels: fix
