Repository SpaiR/imgui-java, pull requests merged in 2023-09, with the labels that each got.

#197 [API] Fix native loading by stopping creating tmpDir every time
  imgui-binding/build.gradle
  imgui-binding/src/main/java/imgui/ImGui.java
Labels: enhancement

#203 Move LICENSE into META-INF folder
  build.gradle
Labels: tweak

#204 Simplify version get from imgui-java.properties file
  imgui-binding/build.gradle
  imgui-binding/src/main/java/imgui/ImGui.java
  imgui-binding/src/main/resources/imgui/imgui-java.properties
Labels: tweak

#205 Bump org.lwjgl:lwjgl from 3.3.2 to 3.3.3
  README.md
  build.gradle
Labels: dependencies
