Repository SpaiR/imgui-java, pull requests merged in 2024-08, with the labels that each got.

#241 build(deps): bump com.gradleup.shadow from 7.1.2 to 8.3.0
  imgui-app/build.gradle
Labels: dependencies, java

#242 build(deps): bump com.badlogicgames.gdx:gdx-jnigen from 2.4.0 to 2.5.1
  buildSrc/build.gradle.kts
  buildSrc/src/main/groovy/tool/generator/GenerateLibs.groovy
Labels: dependencies, java

#243 Refactor GenerateAst task
  buildSrc/src/main/kotlin/tool/generator/ast/decl.kt
  buildSrc/src/main/kotlin/tool/generator/ast/task/GenerateAst.kt
  buildSrc/src/main/resources/generator/api/ast/ast-ImGuiFileDialog.json
  buildSrc/src/main/resources/generator/api/ast/ast-ImGuizmo.json
  buildSrc/src/main/resources/generator/api/ast/ast-TextEditor.json
  buildSrc/src/main/resources/generator/api/ast/ast-imgui-knobs.json
  buildSrc/src/main/resources/generator/api/ast/ast-imgui.json
  buildSrc/src/main/resources/generator/api/ast/ast-imgui_internal.json
  buildSrc/src/main/resources/generator/api/ast/ast-imgui_node_editor.json
  buildSrc/src/main/resources/generator/api/ast/ast-imnodes.json
  buildSrc/src/main/resources/generator/api/ast/ast-implot.json
Labels: fix

#246 Add missing ImGui.TableGetSortSpecs API (and related objects)
  imgui-binding/src/generated/java/imgui/ImGui.java
  imgui-binding/src/generated/java/imgui/ImGuiTableColumnSortSpecs.java
  imgui-binding/src/generated/java/imgui/ImGuiTableSortSpecs.java
  imgui-binding/src/main/java/imgui/ImGui.java
  imgui-binding/src/main/java/imgui/ImGuiTableColumnSortSpecs.java
  imgui-binding/src/main/java/imgui/ImGuiTableSortSpecs.java
Labels: enhancement, api

#254 FreeType is a toggleable option which is disabled by default
  .gitignore
  build.gradle
  buildSrc/scripts/vendor_freetype.sh
  buildSrc/src/main/groovy/tool/generator/GenerateLibs.groovy
  buildSrc/src/main/kotlin/tool/generator/ast/task/GenerateAst.kt
  buildSrc/src/main/resources/generator/api/ast/_gen_ast.sh
  buildSrc/src/main/resources/generator/api/ast/ast-imgui_freetype.json
  example/src/main/java/Main.java
  imgui-binding/src/generated/java/imgui/ImFontAtlas.java
  imgui-binding/src/generated/java/imgui/flag/ImGuiFreeTypeBuilderFlags.java
  imgui-binding/src/main/java/imgui/ImFontAtlas.java
  imgui-binding/src/main/java/imgui/flag/ImGuiFreeTypeBuilderFlags.java
  imgui-binding/src/main/native/imconfig.h
  vendor/freetype-2.12.1.tar.gz
  vendor/freetype-2.13.3.tar.gz
Labels: enhancement, api

#255 Add setup-gradle action
  .github/workflows/ci.yml
Labels: enhancement

#263 Create unwrapped methods for methods with dst arg
  buildSrc/src/main/kotlin/tool/generator/api/jni_content.kt
  buildSrc/src/main/kotlin/tool/generator/api/jvm_content.kt
  imgui-binding/src/generated/java/imgui/ImGui.java
  imgui-binding/src/generated/java/imgui/extension/implot/ImPlot.java
  imgui-binding/src/generated/java/imgui/extension/nodeditor/NodeEditor.java
  imgui-binding/src/generated/java/imgui/internal/ImGui.java
  imgui-binding/src/main/java/imgui/ImGui.java
Labels: enhancement

#264 ArgVariant annotation and plot methods with count parameter
  buildSrc/src/main/kotlin/tool/generator/api/BindingSourceProcessor.kt
  buildSrc/src/main/kotlin/tool/generator/api/jni_content.kt
  buildSrc/src/main/kotlin/tool/generator/api/jvm_content.kt
  buildSrc/src/main/kotlin/tool/generator/api/util.kt
  imgui-binding/src/generated/java/imgui/extension/implot/ImPlot.java
  imgui-binding/src/main/java/imgui/ImGui.java
  imgui-binding/src/main/java/imgui/binding/annotation/ArgVariant.java
  imgui-binding/src/main/java/imgui/extension/implot/ImPlot.java
Labels: enhancement, api

#265 Change pointers casting type
  buildSrc/scripts/publish.sh
  buildSrc/src/main/kotlin/tool/generator/api/util.kt
  imgui-binding/src/generated/java/imgui/ImDrawData.java
  imgui-binding/src/generated/java/imgui/ImDrawList.java
  imgui-binding/src/generated/java/imgui/ImFont.java
  imgui-binding/src/generated/java/imgui/ImFontAtlas.java
  imgui-binding/src/generated/java/imgui/ImFontConfig.java
  imgui-binding/src/generated/java/imgui/ImFontGlyph.java
  imgui-binding/src/generated/java/imgui/ImGui.java
  imgui-binding/src/generated/java/imgui/ImGuiIO.java
  imgui-binding/src/generated/java/imgui/ImGuiKeyData.java
  imgui-binding/src/generated/java/imgui/ImGuiPlatformIO.java
  imgui-binding/src/generated/java/imgui/ImGuiStorage.java
  imgui-binding/src/generated/java/imgui/ImGuiStyle.java
  imgui-binding/src/generated/java/imgui/ImGuiTableSortSpecs.java
  imgui-binding/src/generated/java/imgui/ImGuiTextFilter.java
  imgui-binding/src/generated/java/imgui/ImGuiViewport.java
  imgui-binding/src/generated/java/imgui/ImGuiWindowClass.java
  imgui-binding/src/generated/java/imgui/extension/imguifiledialog/ImGuiFileDialog.java
  imgui-binding/src/generated/java/imgui/extension/imnodes/ImNodes.java
  imgui-binding/src/generated/java/imgui/extension/implot/ImPlot.java
  imgui-binding/src/generated/java/imgui/extension/implot/ImPlotInputMap.java
  imgui-binding/src/generated/java/imgui/extension/implot/ImPlotStyle.java
  imgui-binding/src/generated/java/imgui/extension/memedit/MemoryEditor.java
  imgui-binding/src/generated/java/imgui/extension/memedit/MemoryEditorSizes.java
  imgui-binding/src/generated/java/imgui/extension/nodeditor/NodeEditor.java
  imgui-binding/src/generated/java/imgui/extension/nodeditor/NodeEditorConfig.java
  imgui-binding/src/generated/java/imgui/extension/texteditor/TextEditor.java
  imgui-binding/src/generated/java/imgui/extension/texteditor/TextEditorLanguageDefinition.java
  imgui-binding/src/generated/java/imgui/internal/ImGui.java
  imgui-binding/src/generated/java/imgui/internal/ImGuiDockNode.java
  imgui-binding/src/main/java/imgui/ImDrawData.java
  imgui-binding/src/main/java/imgui/ImDrawList.java
  imgui-binding/src/main/java/imgui/ImFont.java
  imgui-binding/src/main/java/imgui/ImFontAtlas.java
  imgui-binding/src/main/java/imgui/ImFontConfig.java
  imgui-binding/src/main/java/imgui/ImFontGlyph.java
  imgui-binding/src/main/java/imgui/ImGui.java
  imgui-binding/src/main/java/imgui/ImGuiKeyData.java
  imgui-binding/src/main/java/imgui/ImGuiPlatformIO.java
  imgui-binding/src/main/java/imgui/ImGuiStorage.java
  imgui-binding/src/main/java/imgui/ImGuiStyle.java
  imgui-binding/src/main/java/imgui/ImGuiTableSortSpecs.java
  imgui-binding/src/main/java/imgui/ImGuiTextFilter.java
  imgui-binding/src/main/java/imgui/ImGuiViewport.java
  imgui-binding/src/main/java/imgui/ImGuiWindowClass.java
  imgui-binding/src/main/java/imgui/extension/imguifiledialog/ImGuiFileDialog.java
  imgui-binding/src/main/java/imgui/extension/implot/ImPlot.java
  imgui-binding/src/main/java/imgui/extension/implot/ImPlotInputMap.java
  imgui-binding/src/main/java/imgui/extension/implot/ImPlotStyle.java
  imgui-binding/src/main/java/imgui/extension/memedit/MemoryEditor.java
  imgui-binding/src/main/java/imgui/extension/memedit/MemoryEditorSizes.java
  imgui-binding/src/main/java/imgui/extension/nodeditor/NodeEditor.java
  imgui-binding/src/main/java/imgui/extension/nodeditor/NodeEditorConfig.java
  imgui-binding/src/main/java/imgui/extension/texteditor/TextEditor.java
  imgui-binding/src/main/java/imgui/extension/texteditor/TextEditorLanguageDefinition.java
  imgui-binding/src/main/java/imgui/internal/ImGuiDockNode.java
  imgui-binding/src/main/native/jni_common.cpp
Labels: enhancement, api
